name: ##CONDA_ENV_NAME##
channels:
- defaults
dependencies:
- python=3.7.7
# Packages for Jupyter notebook
- jupyter_client=6.1.6
- jupyter_core=4.6.1
- jupyterlab=2.2.6
- jupyterlab_server=1.2.0
- notebook=6.0.3
- openssl=1.1.1g
- tornado=6.0.4
- cryptography=3.1
- pip:
  - jupyter-enterprise-gateway==2.1.1
