name: ##CONDA_ENV_NAME##
channels:
  - ##CONDA_OPENCE_CHANNEL##
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - asn1crypto=1.4.0
  - attrs=20.1.0
  - backcall=0.2.0
  - bleach=3.1.5
  - ca-certificates=2020.7.22
  - certifi=2020.6.20
  - cffi=1.14.2
  - chardet=3.0.4
  - conda-package-handling=1.6.1
  - cryptography=3.1
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - gmp=6.1.2
  - idna=2.10
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - jinja2=2.11.2
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.6
  - jupyter_core=4.6.1
  - jupyterlab=2.2.6
  - jupyterlab_server=1.2.0
  - ld_impl_linux-ppc64le=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=8.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=8.2.0
  - markupsafe=1.1.1
  - mistune=0.8.4
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - notebook=6.0.3
  - openssl=1.1.1g
  - pandoc=2.2.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.2.2
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.7
  - prompt_toolkit=3.0.7
  - ptyprocess=0.6.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.7.7
  - python-dateutil=2.8.1
  - pyyaml=5.1.2
  - pyzmq=19.0.1
  - readline=8.0
  - requests=2.24.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - six=1.13.0
  - sqlite=3.33.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.0.4
  - tqdm=4.48.2
  - traitlets=4.3.3
  - urllib3=1.25.10
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - xz=5.2.5
  - yaml=0.1.7
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - bcrypt==3.2.0
    - cachetools==4.1.1
    - docker==4.3.1
    - future==0.18.2
    - google-auth==1.21.1
    - jupyter-enterprise-gateway==2.1.1
    - kubernetes==11.0.0
    - oauthlib==3.1.0
    - paramiko==2.7.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycryptodomex==3.9.8
    - pynacl==1.4.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - websocket-client==0.57.0
    - yarn-api-client==1.0.2
