name: ##CONDA_ENV_NAME##
channels:
- ##CONDA_OPENCE_CHANNEL##
- conda-forge
- defaults
dependencies:
- defaults::cudatoolkit==11.0.*
- pip
# Open-CE required framework
- tensorflow==2.4.1
- tensorflow-datasets==4.1.0
- tensorboard==2.4.1
- pytorch==1.7.1
- torchvision==0.8.2
- opencv==3.4.10
- py-xgboost-cpu==1.3.3
# Open-CE optional framework
#- libevent==2.1.11
#- tensorflow-serving==2.4.1
#- dm-tree==0.1.5
#- tensorflow-probability==0.12.1
#- tensorflow-estimator==2.4.0
#- tensorflow-hub==0.10.0
#- tensorflow-text==2.4.1
#- tensorflow-model-optimization==0.5.0
#- tensorflow-addons==0.11.2
# Packages for Jupyter notebook
- jupyter_client=6.1.6
- jupyter_core=4.6.1
- jupyterlab=2.2.6
- jupyterlab_server=1.2.0
- notebook=6.0.3
- openssl=1.1.1g
- tornado=6.0.4
- cryptography=3.1
# Additional packages
- seaborn
- matplotlib
- scikit-learn
# Elyra
- elyra
- git
- pip:
  - keras2onnx==1.6.1
  - gensim==3.8.0
  - jupyter-enterprise-gateway==2.1.1
